### PR TITLE
Fix resend registration message link not working on paged results (fixes #17)

### LINKED ISSUE #17: Fix Resend email links on paged views of the ESPRESSO_MY_EVENTS shortcode output
Originally reported in:
https://events.codebasehq.com/projects/event-espresso/tickets/11327

Page one links work okay, but if you go to a paged view (like page 2) the URL for the resend email link looks something like this:

http://local.wordpress.test/wp-admin/admin-ajax.php?token=1-18f98f4a607ca1ddd733fbee3544006d&resend=1

Normally the admin-ajax.php part isn't included in the URL, and with it there, emails do not send.

### PR DESCRIPTION
**Pull request by nerrad**
## Problem this Pull Request solves

This fixes the issue reported in #17.  However it's still less than an _ideal_ fix:

- clicking the resend link does resend the registration but the page is reloaded after and the results will be on the first page.
- I don't think this will work well if the shortcode is used in a widget.

However in order to resolve the above issues:

- We will need the js to receive routing information from the url so redirect urls can go to a specific loaded page in the my events shortcode output.
- A more resilient option other than `get_permalink()` will be needed to get the current page loaded (not just the url for the current `$post` global state).   Doing this will also complicate the "return" after resending because there may be more than one "my events" output in the view depending on how things are setup.

Ideally, it'd be good to refactor this view as a react app and have all all actions done via http request (REST api or admin-ajax) unless there is a link to another page.  That would neatly solve all of the above issues.

**For now**, in the interest of getting a workable solution out for the _majority_ of use-cases, I suggest we roll with the current fix.

## How has this been tested

* [x] Use the `[ESPRESSO_MY_EVENTS]` shortcode on a page.
* [x] View that page while logged in as a user that has registrations to multiple events where the number of events is greater than the per_page limit set via the shortcode.
* [x] Verify that the reported issue is fixed.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by nerrad** [comment]
> although I don't see where the actual redirect is happening

That redirect is processed by the message system in core after processing the message.

**Comment by joshfeck** [comment]
The reported issue is fixed, but there's a PHP notice displayed in the table on the initial page load or a page refresh. 
Screen Shot 2019-06-14 at 5 00 32 PM


The notices goes away if you go to page 2, and it's not there again after you go back to page 1.

**Comment by Pebblo** [comment]
I think for this to work, we'd need to either make `$link` global or pass it along each of the locate_template calls for the templates.

So in `loop-espresso_my_events-event_section.template.php` something like this:

`$template_args = array('registration' => $registration,
                                       'link' => $link,
 );
 $template      = 'content-espresso_my_events-event_section_tickets.template.php';
 EEH_Template::locate_template($template, $template_args, true, false);`

Then in `content-espresso_my_events-event_section_tickets.template.php` pass link along to the next template and so on.

Also, currently this fix doesn't apply to the `simple_list_table`.

If passing the $link var is what needs to be done I can go through an add that to the calls for review if preferred, mainly commented to point out that simple_list_table also needs fixing.

**Comment by nerrad** [comment]
> I think for this to work, we'd need to either make $link global or pass it along each of the locate_template calls for the templates.

Yup, your assessment is correct.  However, I think this bug actually pointed to what may be a better solution involving less code.  If you replace `$link` with `null` in the `...event_section_tickets...` template (do the equivalent for the simple list template too), then that fixes the issue too because it will just return the query part so the link is setup relatively in the dom.

If you want to give a go at that @tony (including removing unnecessary code as a result, we _could_ go that route?

So to be clear, in the template I'm suggesting this:

```php
// resend confirmation email.
        $resend_registration_link = add_query_arg(
            array('token' => $registration->reg_url_link(), 'resend' => true),
            $link
        );
```

... would become

```php
// resend confirmation email.
        $resend_registration_link = add_query_arg(
            array('token' => $registration->reg_url_link(), 'resend' => true),
            null
        );
```

**Comment by Pebblo** [comment]
How's that?

The only thing I noticed with this is once you've triggered notifications you're directed back to the my events page correctly but you lose the current page you were viewing.

**Comment by joshfeck** [comment]
I'm not so sure it's a requirement that it must work the same if permalinks are set to "plain". Seems like an edge-edge-edge case.

**Comment by nerrad** [comment]
> The only thing I noticed with this is once you've triggered notifications you're directed back to the my events page correctly but you lose the current page you were viewing.

Pretty sure that would have been an issue had this been working in the first place because the page is not being determined from the url so there is nothing to redirect to.  In order to implement paging we'd have to implement hydration via the url.

I can't approve the changes because I created the pull but it has my approval and with Mike's as well (thanks Mike!) I think this is good to go.

**Comment by Pebblo** [comment]
Thanks, guys.

@joshfeck do you want to double check this?

Both the normal and simple list work for me so feel free to merge.

**Comment by joshfeck** [comment]
Yeah works for me.

**Pull request merged**
